# Usa la imagen oficial de .NET 8.0 como base para la ejecución
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

# Usa la imagen del SDK de .NET 8.0 para construir la aplicación
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Project4.csproj", "."]
RUN dotnet restore "Project4.csproj"
COPY . .
RUN dotnet build "Project4.csproj" -c Release -o /app/build

# Publica la aplicación
FROM build AS publish
RUN dotnet publish "Project4.csproj" -c Release -o /app/publish

# Usa la imagen de runtime para ejecutar la aplicación
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://+:80
ENTRYPOINT ["dotnet", "Project4.dll"]
